# SPDX-License-Identifier: None
%YAML 1.2
---
$id: http://devicetree.org/schemas/Bindings/arm/marvell/mvebu-cpu-config.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#
version: 1

title: MVEBU CPU Config registers

maintainers:
  - Gregory CLEMENT <gregory.clement@free-electrons.com>
description: |+
  MVEBU (Marvell SOCs: Armada 370/XP)

             

properties:
  compatible:
    items:
      - enum:
          - marvell,armada-xp-cpu-config
          - marvell,armada-370-cpu-config
    minItems: 1
    maxItems: 1
    additionalItems: false
  reg:
    minItems: 1
    maxItems: 1
    additionalItems: false
examples:
  - |
    cpu-config@21000 {
      compatible = "marvell,armada-xp-cpu-config";
      reg = <0x21000 0x8>;
    };
historical: |+
  MVEBU CPU Config registers
  --------------------------

  MVEBU (Marvell SOCs: Armada 370/XP)

  Required properties:

  - compatible: one of:
  	- "marvell,armada-370-cpu-config"
  	- "marvell,armada-xp-cpu-config"

  - reg: Should contain CPU config registers location and length, in
    their per-CPU variant

...
